### ISSUE TITLE
Additional 'authorized' label when one of the specific developers approves

### ISSUE THREAD

**Issue by kyagi** [kyagi/shamshir#21]
## Example
|name|title|
|---|---|
|Alice|Engineer|
|Bob|Engineer|
|Carol|Principal Engineer|
|Daniel|Engineer|
|Zophie|CTO|

|pull request|approved by|label(s)|
|---|---|---|
|pr 1|Alice, Bob|releasable|
|pr 2|Alice, Bob, Daniel|releasable|
|pr 3|Bob, Carol|releasable, authorized|
|pr 4|Carol|n/a|
|pr 5|Zophie|releasable, authorized|

## Requirements
To implement this feature, another inputs such as `authorized_users` will be required.

action.yml
```
(... snip ...)
inputs:
  quorum:
    description: 'The quorum of approval'
    required: true
  authorized_label:
    description: 'The authorized label name'
    required: false
  authorized_users:
    description: 'The authorized users'
    required: false
  privileged_user:
    description: 'The privileged user'
    required: false
```
    
.github/workflow/shamshir.yml
```
        (... snip ...)
        with:
          (... snip ...)
          label: 'releasable'
          quorum: '2'
          authorized_label: 'authorized'
          authorized_users:
            - name: 'Carol'
          privileged_user:
            - name: 'Zophie'          
```
